/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    FeaturedShiftsResponse,
    FeaturedShiftsResponseFromJSON,
    FeaturedShiftsResponseToJSON,
    NewShiftsResponse,
    NewShiftsResponseFromJSON,
    NewShiftsResponseToJSON,
    PopularShiftsResponse,
    PopularShiftsResponseFromJSON,
    PopularShiftsResponseToJSON,
} from '../models';

/**
 * 
 */
export class FPNApi extends runtime.BaseAPI {

    /**
     * The new shifts to display on the home page.
     */
    async _newRaw(): Promise<runtime.ApiResponse<NewShiftsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/shift/new`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => NewShiftsResponseFromJSON(jsonValue));
    }

    /**
     * The new shifts to display on the home page.
     */
    async _new(): Promise<NewShiftsResponse> {
        const response = await this._newRaw();
        return await response.value();
    }

    /**
     * The featured shifts to display on the home page.
     */
    async featuredRaw(): Promise<runtime.ApiResponse<FeaturedShiftsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/shift/featured`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => FeaturedShiftsResponseFromJSON(jsonValue));
    }

    /**
     * The featured shifts to display on the home page.
     */
    async featured(): Promise<FeaturedShiftsResponse> {
        const response = await this.featuredRaw();
        return await response.value();
    }

    /**
     * The popular shifts to display on the home page.
     */
    async popularRaw(): Promise<runtime.ApiResponse<PopularShiftsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/shift/popular`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PopularShiftsResponseFromJSON(jsonValue));
    }

    /**
     * The popular shifts to display on the home page.
     */
    async popular(): Promise<PopularShiftsResponse> {
        const response = await this.popularRaw();
        return await response.value();
    }

}
