/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    LoadDataResponse,
    LoadDataResponseFromJSON,
    LoadDataResponseToJSON,
} from '../models';

export interface LoadDataRequest {
    trainingDataTypes: Array<string>;
}

/**
 * 
 */
export class LoadApi extends runtime.BaseAPI {

    /**
     * Given training data Shift specializes a model for the training data. Yeilds more relaisitic results than just an inference though it takes longer.
     */
    async loadDataRaw(requestParameters: LoadDataRequest): Promise<runtime.ApiResponse<LoadDataResponse>> {
        if (requestParameters.trainingDataTypes === null || requestParameters.trainingDataTypes === undefined) {
            throw new runtime.RequiredError('trainingDataTypes','Required parameter requestParameters.trainingDataTypes was null or undefined when calling loadData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.trainingDataTypes) {
            headerParameters['trainingDataTypes'] = requestParameters.trainingDataTypes.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const response = await this.request({
            path: `/api/loadData`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => LoadDataResponseFromJSON(jsonValue));
    }

    /**
     * Given training data Shift specializes a model for the training data. Yeilds more relaisitic results than just an inference though it takes longer.
     */
    async loadData(requestParameters: LoadDataRequest): Promise<LoadDataResponse> {
        const response = await this.loadDataRaw(requestParameters);
        return await response.value();
    }

}
