/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Shift,
    ShiftFromJSON,
    ShiftFromJSONTyped,
    ShiftToJSON,
} from './';

/**
 * 
 * @export
 * @interface FeaturedShiftsResponse
 */
export interface FeaturedShiftsResponse {
    /**
     * 
     * @type {Array<Shift>}
     * @memberof FeaturedShiftsResponse
     */
    shifts?: Array<Shift>;
}

export function FeaturedShiftsResponseFromJSON(json: any): FeaturedShiftsResponse {
    return FeaturedShiftsResponseFromJSONTyped(json, false);
}

export function FeaturedShiftsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeaturedShiftsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shifts': !exists(json, 'shifts') ? undefined : ((json['shifts'] as Array<any>).map(ShiftFromJSON)),
    };
}

export function FeaturedShiftsResponseToJSON(value?: FeaturedShiftsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shifts': value.shifts === undefined ? undefined : ((value.shifts as Array<any>).map(ShiftToJSON)),
    };
}


