/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Shift,
    ShiftFromJSON,
    ShiftFromJSONTyped,
    ShiftToJSON,
} from './';

/**
 * 
 * @export
 * @interface IndividualShiftGetResponse
 */
export interface IndividualShiftGetResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IndividualShiftGetResponse
     */
    owner: boolean;
    /**
     * 
     * @type {Shift}
     * @memberof IndividualShiftGetResponse
     */
    shift?: Shift;
}

export function IndividualShiftGetResponseFromJSON(json: any): IndividualShiftGetResponse {
    return IndividualShiftGetResponseFromJSONTyped(json, false);
}

export function IndividualShiftGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualShiftGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'owner': json['owner'],
        'shift': !exists(json, 'shift') ? undefined : ShiftFromJSON(json['shift']),
    };
}

export function IndividualShiftGetResponseToJSON(value?: IndividualShiftGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'owner': value.owner,
        'shift': ShiftToJSON(value.shift),
    };
}


