/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Shift
 */
export interface Shift {
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    baseDecoderPath: string;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    datePosted?: string;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    encoderPath: string;
    /**
     * 
     * @type {object}
     * @memberof Shift
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    imagePath?: string;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    maskDecoderPath: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shift
     */
    _private?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    title: string;
    /**
     * 
     * @type {object}
     * @memberof Shift
     */
    userID: object;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    uuid: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shift
     */
    verified?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Shift
     */
    views?: number;
}

export function ShiftFromJSON(json: any): Shift {
    return ShiftFromJSONTyped(json, false);
}

export function ShiftFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shift {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'baseDecoderPath': json['baseDecoderPath'],
        'datePosted': !exists(json, 'datePosted') ? undefined : json['datePosted'],
        'encoderPath': json['encoderPath'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'imagePath': !exists(json, 'imagePath') ? undefined : json['imagePath'],
        'maskDecoderPath': json['maskDecoderPath'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
        'title': json['title'],
        'userID': json['userID'],
        'uuid': json['uuid'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
        'views': !exists(json, 'views') ? undefined : json['views'],
    };
}

export function ShiftToJSON(value?: Shift | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'baseDecoderPath': value.baseDecoderPath,
        'datePosted': value.datePosted,
        'encoderPath': value.encoderPath,
        'id': value.id,
        'imagePath': value.imagePath,
        'maskDecoderPath': value.maskDecoderPath,
        'private': value._private,
        'title': value.title,
        'userID': value.userID,
        'uuid': value.uuid,
        'verified': value.verified,
        'views': value.views,
    };
}


