/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrainStatusResponse
 */
export interface TrainStatusResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof TrainStatusResponse
     */
    exhibit?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof TrainStatusResponse
     */
    msg?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrainStatusResponse
     */
    stopped?: boolean | null;
}

export function TrainStatusResponseFromJSON(json: any): TrainStatusResponse {
    return TrainStatusResponseFromJSONTyped(json, false);
}

export function TrainStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exhibit': !exists(json, 'exhibit') ? undefined : json['exhibit'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'stopped': !exists(json, 'stopped') ? undefined : json['stopped'],
    };
}

export function TrainStatusResponseToJSON(value?: TrainStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exhibit': value.exhibit,
        'msg': value.msg,
        'stopped': value.stopped,
    };
}


