/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface AuthenticatedResponse
 */
export interface AuthenticatedResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticatedResponse
     */
    authenticated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticatedResponse
     */
    msg?: string;
    /**
     * 
     * @type {User}
     * @memberof AuthenticatedResponse
     */
    user?: User;
}

export function AuthenticatedResponseFromJSON(json: any): AuthenticatedResponse {
    return AuthenticatedResponseFromJSONTyped(json, false);
}

export function AuthenticatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authenticated': !exists(json, 'authenticated') ? undefined : json['authenticated'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function AuthenticatedResponseToJSON(value?: AuthenticatedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authenticated': value.authenticated,
        'msg': value.msg,
        'user': UserToJSON(value.user),
    };
}


