/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordResponse
 */
export interface ChangePasswordResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ChangePasswordResponse
     */
    complete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordResponse
     */
    currentPasswordMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordResponse
     */
    msg?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordResponse
     */
    newPasswordMessage?: string;
}

export function ChangePasswordResponseFromJSON(json: any): ChangePasswordResponse {
    return ChangePasswordResponseFromJSONTyped(json, false);
}

export function ChangePasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'complete': !exists(json, 'complete') ? undefined : json['complete'],
        'currentPasswordMessage': !exists(json, 'currentPasswordMessage') ? undefined : json['currentPasswordMessage'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'newPasswordMessage': !exists(json, 'newPasswordMessage') ? undefined : json['newPasswordMessage'],
    };
}

export function ChangePasswordResponseToJSON(value?: ChangePasswordResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'complete': value.complete,
        'currentPasswordMessage': value.currentPasswordMessage,
        'msg': value.msg,
        'newPasswordMessage': value.newPasswordMessage,
    };
}


