/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmEmailResponse
 */
export interface ConfirmEmailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmEmailResponse
     */
    confirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfirmEmailResponse
     */
    msg?: string | null;
}

export function ConfirmEmailResponseFromJSON(json: any): ConfirmEmailResponse {
    return ConfirmEmailResponseFromJSONTyped(json, false);
}

export function ConfirmEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmEmailResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'confirmed': !exists(json, 'confirmed') ? undefined : json['confirmed'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function ConfirmEmailResponseToJSON(value?: ConfirmEmailResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'confirmed': value.confirmed,
        'msg': value.msg,
    };
}


