/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmEmailChangeResponse
 */
export interface ConfirmEmailChangeResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmEmailChangeResponse
     */
    confirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfirmEmailChangeResponse
     */
    msg?: string | null;
}

export function ConfirmEmailChangeResponseFromJSON(json: any): ConfirmEmailChangeResponse {
    return ConfirmEmailChangeResponseFromJSONTyped(json, false);
}

export function ConfirmEmailChangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmEmailChangeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'confirmed': !exists(json, 'confirmed') ? undefined : json['confirmed'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function ConfirmEmailChangeResponseToJSON(value?: ConfirmEmailChangeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'confirmed': value.confirmed,
        'msg': value.msg,
    };
}


