/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordResponse
 */
export interface ForgotPasswordResponse {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResponse
     */
    currentPasswordMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResponse
     */
    msg?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResponse
     */
    newPasswordMessage?: string;
}

export function ForgotPasswordResponseFromJSON(json: any): ForgotPasswordResponse {
    return ForgotPasswordResponseFromJSONTyped(json, false);
}

export function ForgotPasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPasswordMessage': !exists(json, 'currentPasswordMessage') ? undefined : json['currentPasswordMessage'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'newPasswordMessage': !exists(json, 'newPasswordMessage') ? undefined : json['newPasswordMessage'],
    };
}

export function ForgotPasswordResponseToJSON(value?: ForgotPasswordResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentPasswordMessage': value.currentPasswordMessage,
        'msg': value.msg,
        'newPasswordMessage': value.newPasswordMessage,
    };
}


