/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InferenceRequest
 */
export interface InferenceRequest {
    /**
     * 
     * @type {string}
     * @memberof InferenceRequest
     */
    prebuiltShiftModel?: string;
    /**
     * 
     * @type {string}
     * @memberof InferenceRequest
     */
    shiftUUID: string;
    /**
     * 
     * @type {boolean}
     * @memberof InferenceRequest
     */
    training?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InferenceRequest
     */
    usePTM?: boolean;
}

export function InferenceRequestFromJSON(json: any): InferenceRequest {
    return InferenceRequestFromJSONTyped(json, false);
}

export function InferenceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InferenceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prebuiltShiftModel': !exists(json, 'prebuiltShiftModel') ? undefined : json['prebuiltShiftModel'],
        'shiftUUID': json['shiftUUID'],
        'training': !exists(json, 'training') ? undefined : json['training'],
        'usePTM': !exists(json, 'usePTM') ? undefined : json['usePTM'],
    };
}

export function InferenceRequestToJSON(value?: InferenceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prebuiltShiftModel': value.prebuiltShiftModel,
        'shiftUUID': value.shiftUUID,
        'training': value.training,
        'usePTM': value.usePTM,
    };
}


