/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshResponse
 */
export interface RefreshResponse {
    /**
     * 
     * @type {string}
     * @memberof RefreshResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof RefreshResponse
     */
    msg?: string | null;
}

export function RefreshResponseFromJSON(json: any): RefreshResponse {
    return RefreshResponseFromJSONTyped(json, false);
}

export function RefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function RefreshResponseToJSON(value?: RefreshResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'msg': value.msg,
    };
}


