/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterResponse
 */
export interface RegisterResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    emailMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    msg?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    passwordMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    usernameMessage?: string;
}

export function RegisterResponseFromJSON(json: any): RegisterResponse {
    return RegisterResponseFromJSONTyped(json, false);
}

export function RegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'emailMessage': !exists(json, 'emailMessage') ? undefined : json['emailMessage'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'passwordMessage': !exists(json, 'passwordMessage') ? undefined : json['passwordMessage'],
        'usernameMessage': !exists(json, 'usernameMessage') ? undefined : json['usernameMessage'],
    };
}

export function RegisterResponseToJSON(value?: RegisterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'emailMessage': value.emailMessage,
        'msg': value.msg,
        'passwordMessage': value.passwordMessage,
        'usernameMessage': value.usernameMessage,
    };
}


