/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendConfirmEmailResponse
 */
export interface ResendConfirmEmailResponse {
    /**
     * 
     * @type {string}
     * @memberof ResendConfirmEmailResponse
     */
    msg?: string | null;
}

export function ResendConfirmEmailResponseFromJSON(json: any): ResendConfirmEmailResponse {
    return ResendConfirmEmailResponseFromJSONTyped(json, false);
}

export function ResendConfirmEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendConfirmEmailResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function ResendConfirmEmailResponseToJSON(value?: ResendConfirmEmailResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
    };
}


