/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface Shift
 */
export interface Shift {
    /**
     * 
     * @type {User}
     * @memberof Shift
     */
    author: User;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    baseMediaFilename?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof Shift
     */
    categories?: Array<object>;
    /**
     * 
     * @type {Date}
     * @memberof Shift
     */
    dateCreated?: Date;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    maskMediaFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    mediaFilename?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shift
     */
    _private?: boolean;
    /**
     * 
     * @type {Array<object>}
     * @memberof Shift
     */
    shiftCategories?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    uuid: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shift
     */
    verified?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Shift
     */
    views?: number;
}

export function ShiftFromJSON(json: any): Shift {
    return ShiftFromJSONTyped(json, false);
}

export function ShiftFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shift {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': UserFromJSON(json['author']),
        'baseMediaFilename': !exists(json, 'baseMediaFilename') ? undefined : json['baseMediaFilename'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'dateCreated': !exists(json, 'dateCreated') ? undefined : (new Date(json['dateCreated'])),
        'maskMediaFilename': !exists(json, 'maskMediaFilename') ? undefined : json['maskMediaFilename'],
        'mediaFilename': !exists(json, 'mediaFilename') ? undefined : json['mediaFilename'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
        'shiftCategories': !exists(json, 'shiftCategories') ? undefined : json['shiftCategories'],
        'title': json['title'],
        'uuid': json['uuid'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
        'views': !exists(json, 'views') ? undefined : json['views'],
    };
}

export function ShiftToJSON(value?: Shift | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': UserToJSON(value.author),
        'baseMediaFilename': value.baseMediaFilename,
        'categories': value.categories,
        'dateCreated': value.dateCreated === undefined ? undefined : (value.dateCreated.toISOString()),
        'maskMediaFilename': value.maskMediaFilename,
        'mediaFilename': value.mediaFilename,
        'private': value._private,
        'shiftCategories': value.shiftCategories,
        'title': value.title,
        'uuid': value.uuid,
        'verified': value.verified,
        'views': value.views,
    };
}


