/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeCreateCheckoutSessionResponse
 */
export interface StripeCreateCheckoutSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof StripeCreateCheckoutSessionResponse
     */
    sessionId?: string;
}

export function StripeCreateCheckoutSessionResponseFromJSON(json: any): StripeCreateCheckoutSessionResponse {
    return StripeCreateCheckoutSessionResponseFromJSONTyped(json, false);
}

export function StripeCreateCheckoutSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCreateCheckoutSessionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
    };
}

export function StripeCreateCheckoutSessionResponseToJSON(value?: StripeCreateCheckoutSessionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sessionId': value.sessionId,
    };
}


