/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripePublishableKeyResponse
 */
export interface StripePublishableKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof StripePublishableKeyResponse
     */
    publicKey: string;
}

export function StripePublishableKeyResponseFromJSON(json: any): StripePublishableKeyResponse {
    return StripePublishableKeyResponseFromJSONTyped(json, false);
}

export function StripePublishableKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripePublishableKeyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicKey': json['publicKey'],
    };
}

export function StripePublishableKeyResponseToJSON(value?: StripePublishableKeyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicKey': value.publicKey,
    };
}


