/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FeryvUser,
    FeryvUserFromJSON,
    FeryvUserFromJSONTyped,
    FeryvUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    admin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    canTrain?: boolean;
    /**
     * 
     * @type {FeryvUser}
     * @memberof User
     */
    feryvUser?: FeryvUser;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof User
     */
    shifts?: Array<object>;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    verified?: boolean;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'admin': !exists(json, 'admin') ? undefined : json['admin'],
        'canTrain': !exists(json, 'canTrain') ? undefined : json['canTrain'],
        'feryvUser': !exists(json, 'feryvUser') ? undefined : FeryvUserFromJSON(json['feryvUser']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'shifts': !exists(json, 'shifts') ? undefined : json['shifts'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'admin': value.admin,
        'canTrain': value.canTrain,
        'feryvUser': FeryvUserToJSON(value.feryvUser),
        'id': value.id,
        'shifts': value.shifts,
        'verified': value.verified,
    };
}


