/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    admin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    canTrain?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    dateCreated?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {object}
     * @memberof User
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    mediaFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    verified?: boolean;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'admin': !exists(json, 'admin') ? undefined : json['admin'],
        'canTrain': !exists(json, 'canTrain') ? undefined : json['canTrain'],
        'dateCreated': !exists(json, 'dateCreated') ? undefined : json['dateCreated'],
        'email': json['email'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'mediaFilename': !exists(json, 'mediaFilename') ? undefined : json['mediaFilename'],
        'username': json['username'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'admin': value.admin,
        'canTrain': value.canTrain,
        'dateCreated': value.dateCreated,
        'email': value.email,
        'id': value.id,
        'mediaFilename': value.mediaFilename,
        'username': value.username,
        'verified': value.verified,
    };
}


